### ISSUE TITLE
如何运行main?

### ISSUE THREAD

**Issue by Corezcy** [flamywhale/simple-http-server#2]
您好，我现在学习您的代码，现在已经安装了evhttp，如何运行您的代码呢？我想试一下上传下载，谢谢了！

**Comment by Corezcy** [comment]
国科大学长？？？

**Comment by wujiahao15** [comment]
> 您好，我现在学习您的代码，现在已经安装了evhttp，如何运行您的代码呢？我想试一下上传下载，谢谢了！

在`git clone`这个代码仓库后，执行以下步骤：
1. `git checkout evhttp-version`：将git的分支切换到`evhttp-version`
2. 在该目录下运行`make all`
3. 编译成功后，运行`./wuw_server`

**Comment by Corezcy** [comment]
> > 您好，我现在学习您的代码，现在已经安装了evhttp，如何运行您的代码呢？我想试一下上传下载，谢谢了！
> 
> 在`git clone`这个代码仓库后，执行以下步骤：
> 
> 1. `git checkout evhttp-version`：将git的分支切换到`evhttp-version`
> 2. 在该目录下运行`make all`
> 3. 编译成功后，运行`./wuw_server`

好的！还有一个问题向您请教一下，我看您是用浏览器当客户端传文件给C++ 服务器。反过来，我可以实现基于evhttp C++的客户端同服务器（比如flask定义的接口服务器）传递文件吗？谢谢了🙏！

**Comment by wujiahao15** [comment]
> > > 您好，我现在学习您的代码，现在已经安装了evhttp，如何运行您的代码呢？我想试一下上传下载，谢谢了！
> > 
> > 
> > 在`git clone`这个代码仓库后，执行以下步骤：
> > 
> > 1. `git checkout evhttp-version`：将git的分支切换到`evhttp-version`
> > 2. 在该目录下运行`make all`
> > 3. 编译成功后，运行`./wuw_server`
> 
> 好的！还有一个问题向您请教一下，我看您是用浏览器当客户端传文件给C++ 服务器。反过来，我可以实现基于evhttp C++的客户端同服务器（比如flask定义的接口服务器）传递文件吗？谢谢了🙏！

我认为完全可行，我在完成这个课程任务的时候用的是evhttp的服务端接口，而evhttp也有客户端接口。因此，完全可以实现你的那一套逻辑。

抱歉回复慢了，前些天有些事儿。

**Comment by Corezcy** [comment]
> > > > 您好，我现在学习您的代码，现在已经安装了evhttp，如何运行您的代码呢？我想试一下上传下载，谢谢了！
> > > 
> > > 
> > > 在`git clone`这个代码仓库后，执行以下步骤：
> > > 
> > > 1. `git checkout evhttp-version`：将git的分支切换到`evhttp-version`
> > > 2. 在该目录下运行`make all`
> > > 3. 编译成功后，运行`./wuw_server`
> > 
> > 
> > 好的！还有一个问题向您请教一下，我看您是用浏览器当客户端传文件给C++ 服务器。反过来，我可以实现基于evhttp C++的客户端同服务器（比如flask定义的接口服务器）传递文件吗？谢谢了pray！
> 
> 我认为完全可行，我在完成这个课程任务的时候用的是evhttp的服务端接口，而evhttp也有客户端接口。因此，完全可以实现你的那一套逻辑。
> 
> 抱歉回复慢了，前些天有些事儿。

多谢多谢！！！目前在调研C++的网络库，不知道选哪个更好用些！有你这句话就放心了，感谢!
